#!/usr/bin/env python3
"""
Simple LVGL image conversion script.

Usage:
    python tools/convert_to_lvgl.py <input_png> <out_c> [width] [height]

Example:
    python tools/convert_to_lvgl.py assets/rocket.png main/img_rocket_png.c 360 360

This script depends on Pillow. Install with:
    pip install pillow

It will resize the PNG to the requested dimensions (defaults to 360x360), convert to RGB565
and write a C file containing an `lv_img_dsc_t` with name `img_rocket_png`.

Note: For larger images this produces a large array in `img_rocket_png.c` (~2 bytes/pixel).
This is acceptable for embedded builds, but keep memory/perf considerations in mind.
"""
import sys
import os
from PIL import Image


def rgb888_to_rgb565(r, g, b):
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def write_lvgl_c(outfile, img_name, w, h, pixels_rgb565):
    header = f"""#include <stdint.h>
#ifdef __has_include
    #if __has_include("lvgl.h")
        #ifndef LV_LVGL_H_INCLUDE_SIMPLE
            #define LV_LVGL_H_INCLUDE_SIMPLE
        #endif
    #endif
#endif

#if defined(LV_LVGL_H_INCLUDE_SIMPLE)
    #include "lvgl.h"
#else
    #include "lvgl/lvgl.h"
#endif

#ifndef LV_ATTRIBUTE_MEM_ALIGN
#define LV_ATTRIBUTE_MEM_ALIGN
#endif

#ifndef LV_ATTRIBUTE_IMAGE_ROCKET_PNG
#define LV_ATTRIBUTE_IMAGE_ROCKET_PNG
#endif

/* Automatically generated by convert_to_lvgl.py */

    static const
    LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_LARGE_CONST LV_ATTRIBUTE_IMAGE_ROCKET_PNG
    uint8_t img_rocket_{w}x{h}_map[{w}*{h}*2] = {{
"""
    header2 = "};\n\n"
    with open(outfile, "w") as f:
        f.write(header)
        # write pixels
        line_count = 0
        f.write("    ")
        for i, px in enumerate(pixels_rgb565):
            # write as little-endian bytes (low, high)
            lo = px & 0xFF
            hi = (px >> 8) & 0xFF
            f.write(f"0x{lo:02X},0x{hi:02X},")
            line_count += 1
            if line_count >= 12:
                f.write("\n    ")
                line_count = 0
        f.write("\n")
        f.write(header2)
        f.write(f"const lv_img_dsc_t img_rocket_png = {{\n")
        f.write("  .header.magic = LV_IMAGE_HEADER_MAGIC,\n")
        f.write("  .header.cf = LV_COLOR_FORMAT_RGB565,\n")
        f.write("  .header.flags = 0,\n")
        f.write(f"  .header.w = {w},\n")
        f.write(f"  .header.h = {h},\n")
        f.write(f"  .header.stride = {w*2},\n")
        f.write(f"  .data_size = sizeof(img_rocket_{w}x{h}_map),\n")
        f.write(f"  .data = img_rocket_{w}x{h}_map,\n")
        f.write("};\n")


def write_raw_bin(bin_out, w, h, pixels_rgb565):
    # binary format: 4-byte magic 'RKT1', uint16_t width, uint16_t height, then raw little-endian RGB565 bytes
    with open(bin_out, "wb") as bf:
        bf.write(b'RKT1')
        bf.write((w).to_bytes(2, 'little'))
        bf.write((h).to_bytes(2, 'little'))
        for px in pixels_rgb565:
            lo = px & 0xFF
            hi = (px >> 8) & 0xFF
            bf.write(bytes([lo, hi]))


def convert(infile, outfile, width, height):
    img = Image.open(infile)
    if img.mode != 'RGBA' and img.mode != 'RGB':
        img = img.convert('RGBA')
    # Convert and resize
    img = img.resize((width, height), Image.LANCZOS)

    pixels = list(img.getdata())
    # If it's RGBA, composite on white background (or keep simple approach)
    if img.mode == 'RGBA':
        pixels_rgb = []
        for r,g,b,a in pixels:
            # Composite over white
            inva = 255 - a
            r = (r * a + 255 * inva) // 255
            g = (g * a + 255 * inva) // 255
            b = (b * a + 255 * inva) // 255
            pixels_rgb.append((r,g,b))
    else:
        pixels_rgb = pixels

    pixels_rgb565 = [rgb888_to_rgb565(r,g,b) for (r,g,b) in pixels_rgb]
    write_lvgl_c(outfile, 'img_rocket_png', width, height, pixels_rgb565)
    # Also create a raw .bin that can be copied to a device's FS (SPIFFS or SD) to avoid reflashing for images
    bin_out = os.path.splitext(outfile)[0] + ".bin"
    write_raw_bin(bin_out, width, height, pixels_rgb565)
    print(f"Wrote LVGL image file: {outfile}")
    print(f"Wrote raw BIN splash file: {bin_out}")


def main():
    if len(sys.argv) < 3:
        print("Usage: convert_to_lvgl.py <in.png> <out.c> [width] [height]")
        sys.exit(1)
    infile = sys.argv[1]
    outfile = sys.argv[2]
    width = int(sys.argv[3]) if len(sys.argv) > 3 else 360
    height = int(sys.argv[4]) if len(sys.argv) > 4 else 360

    if not os.path.isfile(infile):
        print(f"Input file not found: {infile}")
        sys.exit(2)

    convert(infile, outfile, width, height)
    print(f"Wrote LVGL image file: {outfile}")

if __name__ == '__main__':
    main()
